import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {createScene,clone,diff,SceneStore} from '../public/packages/core/index.js';
import {ProjectClient,compactPatches} from '../public/packages/collaboration/index.js';
import {createLocalTransport,IndexedDBProjectStorage} from '../public/packages/collaboration/local.js';

class MemoryStorage {
  records=new Map(); tail=Promise.resolve();
  async list(){await this.tail;return clone([...this.records.values()]);}
  transact(id,update){const job=this.tail.then(()=>{const record=clone(this.records.get(id)??null);if(!update)return record;const outcome=update(record);if(outcome.record)this.records.set(id,clone(outcome.record));return clone(outcome.result);});this.tail=job.catch(()=>{});return job;}
}
function fixture(){const storage=new MemoryStorage();let id=0,time=0;const request=createLocalTransport({storage,uuid:()=>String(++id),now:()=>++time});return {storage,request};}
async function saved(){const f=fixture();const scene=createScene();const {id}=await f.request('/projects','POST',{scene});return {...f,scene,id};}

test('Local project creation and retrieval isolate data from callers',async()=>{const {request,scene,id}=await saved();scene.name='Uncommitted';const p=await request('/projects/'+id);assert.notEqual(p.scene.name,scene.name);p.scene.name='Mutated read';assert.notEqual((await request('/projects/'+id)).scene.name,p.scene.name);assert.equal((await request('/projects')).projects.length,1);assert.equal((await request('/me')).id,'local-browser');});
test('Local patches persist with monotonically increasing revisions',async()=>{const {request,scene,id}=await saved();const next=clone(scene);next.name='Saved local look';assert.equal((await request('/projects/'+id,'PATCH',{revision:1,patches:diff(scene,next)})).revision,2);const p=await request('/projects/'+id);assert.equal(p.name,next.name);assert.equal(p.revision,2);});
test('Stale local revisions return a conflict snapshot without replacing data',async()=>{const {request,scene,id}=await saved();const next=clone(scene);next.name='Other tab';await request('/projects/'+id,'PATCH',{revision:1,patches:diff(scene,next)});await assert.rejects(request('/projects/'+id,'PATCH',{revision:1,patches:[]}),error=>error.status===409&&error.data.revision===2&&error.data.scene.name==='Other tab');assert.equal((await request('/projects/'+id)).name,'Other tab');});
test('Simultaneous local writes serialize: one succeeds and one conflicts',async()=>{const {request,scene,id}=await saved();const a=clone(scene),b=clone(scene);a.name='A';b.name='B';const results=await Promise.allSettled([a,b].map(next=>request('/projects/'+id,'PATCH',{revision:1,patches:diff(scene,next)})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409);});
test('Local checkpoints retain independent immutable scene snapshots',async()=>{const {request,scene,id}=await saved();const version=await request('/projects/'+id+'/versions','POST',{name:'Original look'});const next=clone(scene);next.name='Later look';await request('/projects/'+id,'PATCH',{revision:1,patches:diff(scene,next)});const list=await request('/projects/'+id+'/versions');assert.equal(list.versions.length,1);assert.ok(!('scene' in list.versions[0]));const snapshot=await request('/projects/'+id+'/versions/'+version.id);assert.equal(snapshot.scene.name,scene.name);assert.equal(snapshot.name,'Original look');});
test('Local mode explicitly rejects server invitations and administration',async()=>{const {request,id}=await saved();for(const path of ['/join','/projects/'+id+'/invites','/projects/'+id+'/members'])await assert.rejects(request(path,'POST',{}),e=>e.status===501);});
test('Invalid local scenes and patch batches cannot create or alter projects',async()=>{const {request,storage,scene,id}=await saved();await assert.rejects(request('/projects','POST',{scene:{}}));await assert.rejects(request('/projects/'+id,'PATCH',{revision:1,patches:'bad'}),e=>e.status===400);assert.equal(storage.records.size,1);assert.equal((await request('/projects/'+id)).scene.name,scene.name);});
test('Unknown projects, checkpoints and operations fail explicitly',async()=>{const {request,id}=await saved();for(const path of ['/projects/missing','/projects/'+id+'/versions/missing','/projects/'+id+'/unknown','/unknown'])await assert.rejects(request(path),e=>e.status===404);});
test('Browser storage denial is surfaced rather than silently pretending to save',async()=>{const storage=new IndexedDBProjectStorage({indexedDB:null});await assert.rejects(storage.open(),e=>e.status===503);const request=createLocalTransport({storage});await assert.rejects(request('/projects'));});
test('ProjectClient can save and reload through an injected local transport',async()=>{const {request}=fixture();const store=new SceneStore();const client=new ProjectClient(store,{transport:request,recovery:false});try{await client.create();store.change('Rename',s=>s.name='Saved by adapter');await client.flush();assert.equal(client.revision,2);assert.equal((await request('/projects/'+client.id)).scene.name,'Saved by adapter');assert.equal(client.pending.length,0);}finally{client.dispose();}});
test('Recovery draft keys isolate browser-local projects from server drafts',()=>{const old=globalThis.localStorage;const saved=new Map();globalThis.localStorage={setItem:(k,v)=>saved.set(k,v),getItem:k=>saved.get(k),removeItem:k=>saved.delete(k)};const client=new ProjectClient(new SceneStore(),{recoveryKey:'pages:/LumeraStudio/'});try{client.persistDraft();assert.ok(saved.has('pages:/LumeraStudio/'));assert.ok(!saved.has('lumera-recovery-v1'));client.resetSession();assert.ok(!saved.has('pages:/LumeraStudio/'));}finally{client.dispose();if(old===undefined)delete globalThis.localStorage;else globalThis.localStorage=old;}});
test('Public compactPatches export agrees with the declaration',()=>{const a=createScene(),b=clone(a);b.name='Different';assert.equal(compactPatches(a,b).length,1);});
test('Pages build rewrites root assets and home links without changing server HTML',async()=>{const original=await readFile(new URL('../public/index.html',import.meta.url),'utf8');const build=spawnSync(process.execPath,['scripts/build-pages.mjs'],{cwd:new URL('..',import.meta.url),encoding:'utf8'});assert.equal(build.status,0,build.stderr);const html=await readFile(new URL('../_site/index.html',import.meta.url),'utf8');assert.match(html,/name="lumera-storage" content="local"/);assert.match(html,/src="\.\/app\/studio.js"/);assert.match(html,/href="\.\/" aria-label="Lumera home"/);assert.ok(!/\b(?:href|src)="\//.test(html));assert.equal(await readFile(new URL('../public/index.html',import.meta.url),'utf8'),original);assert.ok(!original.includes('name="lumera-storage"'));assert.match(await readFile(new URL('../_site/examples/renderer.html',import.meta.url),'utf8'),/\.\.\/packages\/renderer\/index.js/);});
