import {createServer} from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {readFile,mkdir,readdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {api} from './api.js';
const root=resolve(import.meta.dirname,'..');await mkdir(resolve(root,'.local'),{recursive:true});const sqlite=new DatabaseSync(resolve(root,'.local/lumera.sqlite'));sqlite.exec('PRAGMA journal_mode=WAL;');sqlite.exec('CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY)');for(const file of (await readdir(resolve(root,'drizzle'))).filter(n=>n.endsWith('.sql')).sort()){if(!sqlite.prepare('SELECT name FROM _migrations WHERE name=?').get(file)){sqlite.exec(await readFile(resolve(root,'drizzle',file),'utf8'));sqlite.prepare('INSERT INTO _migrations (name) VALUES (?)').run(file)}}
const db={prepare(sql){const statement=sqlite.prepare(sql);let args=[];const wrapped={bind(...values){args=values;return wrapped},async first(){return statement.get(...args)||null},async all(){return{results:statement.all(...args)}},async run(){const r=statement.run(...args);return{meta:{changes:Number(r.changes)}}}};return wrapped},async batch(queries){sqlite.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.png':'image/png'};
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost:3000');if(url.pathname.startsWith('/api/')){const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>2_000_000){res.writeHead(413);res.end();return}chunks.push(chunk)}const request=new Request(url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const response=await api(request,db,{id:'local-user',name:'Local artist',email:'local@lumera'});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text());return}const path=resolve(root,'public','.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname)));if(!path.startsWith(resolve(root,'public')+'/'))throw Error('Invalid path');const data=await readFile(path);res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}});server.listen(3000,'127.0.0.1',()=>console.log('Lumera is running at http://localhost:3000 — local single-user SQLite mode'));
