export type Vec3=[number,number,number];
export type PrimitiveType='sphere'|'box'|'plane'|'torus'|'cylinder';
export interface Material{id:string;name:string;color:string;metallic:number;roughness:number;emission:number}
export interface SceneObject{id:string;name:string;type:PrimitiveType;position:Vec3;rotation:Vec3;scale:Vec3;materialId:string;visible:boolean;group:string}
export interface Light{id:string;name:string;type:'area'|'point';position:Vec3;color:string;intensity:number;exposure:number;radius:number;enabled:boolean;solo:boolean;group:string;links:string[]}
export interface Camera{yaw:number;pitch:number;distance:number;target:Vec3;fov:number}
export interface RenderSettings{samples:number;bounces:number;exposure:number;environment:number;background:string;resolution:number;aov:'beauty'|'albedo'|'normal'|'depth'}
export type NodeType='Scene'|'Primitive'|'Transform'|'Material'|'MaterialAssign'|'LightRig'|'Merge'|'RenderSettings'|'Output';
export interface SceneNode{id:string;type:NodeType;name:string;x:number;y:number;enabled:boolean;params:Record<string,unknown>}
export interface Scene{schemaVersion:1;name:string;objects:SceneObject[];lights:Light[];materials:Material[];nodes:SceneNode[];edges:[string,string][];camera:Camera;settings:RenderSettings;timeline:{frame:number;start:number;end:number;fps:number;keys:{id:string;property:'position'|'rotation'|'scale';keys:{frame:number;value:Vec3}[]}[]};comments:{id:string;text:string;author:string;time:number}[];snapshots:{id:string;name:string;image:string;time:number;samples:number;look:Pick<Scene,'camera'|'settings'|'objects'|'materials'|'lights'>}[]}
export interface Patch{path:string[];before:unknown;value:unknown;remove:boolean}
export class SceneStore extends EventTarget{constructor(scene?:Scene);scene:Scene;selection:{kind:'object'|'light'|'material'|'node';id:string};history:unknown[];future:unknown[];change(label:string,fn:(scene:Scene)=>void):void;replace(scene:Scene,local?:boolean):void;undo():void;redo():void;select(kind:'object'|'light'|'material'|'node',id:string):void}
export const VERSION:string;export const NODE_TYPES:NodeType[];export function uid():string;export function clone<T>(value:T):T;export function clamp(value:number,min:number,max:number):number;export function createScene():Scene;export function validateScene(scene:unknown):Scene;export function evaluateScene(scene:Scene,frame?:number):Scene;export function topologicalSort(nodes:SceneNode[],edges:[string,string][]):string[];export function diff(a:unknown,b:unknown,path?:string[]):Patch[];export function applyPatches(scene:Scene,patches:Patch[],options?:{check?:boolean}):Scene;export function object(type?:PrimitiveType,name?:string):SceneObject;export function light(name?:string):Light;export function material(name:string,color:string,metallic?:number,roughness?:number):Material;export function cameraBasis(camera:Camera):{eye:Vec3;forward:Vec3;right:Vec3;up:Vec3};export function hexLinear(hex:string):Vec3;export function importOBJ(text:string,name?:string):{name:string;vertices:Vec3[];faces:number[][]};
